<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>ApsMonitor-8f829f28-f4bd-4791-baa1-b748f01426fb</UserSecretsId>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <Platforms>AnyCPU;ARM32</Platforms>
    <PublishAot>False</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="artifacts/**" />
    <Content Remove="artifacts/**" />
    <None Remove="artifacts/**" />
    <Compile Remove=".tools/**" />
    <Content Remove=".tools/**" />
    <None Remove=".tools/**" />
    <Compile Remove="tests/**/*.cs" />
    <Content Remove="tests/**" />
    <None Remove="tests/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpPcap" Version="6.3.1" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" Version="9.9.0" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
  </ItemGroup>

</Project>
