// <auto-generated />
using System;
using ApsMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApsMonitor.Migrations
{
    [DbContext(typeof(ApsDbContext))]
    partial class ApsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ApsMonitor.Models.EventMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "OK",
                            Fecha = new DateTime(2023, 3, 20, 12, 13, 14, 0, DateTimeKind.Unspecified),
                            Mensaje = "Arrancar Inversor"
                        });
                });

            modelBuilder.Entity("ApsMonitor.Models.Signal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BitTextoActivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BitTextoInactivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BytePosicion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionEs")
                        .HasColumnType("TEXT");

                    b.Property<double>("Escala")
                        .HasColumnType("REAL");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Offset")
                        .HasColumnType("REAL");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoVariable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorActual")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorInicial")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Signals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BitTextoActivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BitTextoInactivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BytePosicion = 0,
                            Escala = 0.10000000000000001,
                            Formato = "0.01",
                            Nombre = "Tensión Batería",
                            Offset = 0.0,
                            Tag = "V_BAT",
                            TipoVariable = "UINT16",
                            Unidad = "V",
                            ValorActual = 100.91,
                            ValorInicial = 0.0
                        },
                        new
                        {
                            Id = 2,
                            BitTextoActivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BitTextoInactivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BytePosicion = 2,
                            Escala = 0.10000000000000001,
                            Formato = "0.01",
                            Nombre = "Corriente Carga",
                            Offset = 0.0,
                            Tag = "I_CARGA",
                            TipoVariable = "UINT16",
                            Unidad = "A",
                            ValorActual = 23.120000000000001,
                            ValorInicial = 0.0
                        },
                        new
                        {
                            Id = 3,
                            BitTextoActivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BitTextoInactivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BytePosicion = 4,
                            Escala = 0.10000000000000001,
                            Formato = "0.01",
                            Nombre = "Temp. Transformador",
                            Offset = -40.0,
                            Tag = "T_TRANS",
                            TipoVariable = "UINT16",
                            Unidad = "°C",
                            ValorActual = 26.390000000000001,
                            ValorInicial = 0.0
                        },
                        new
                        {
                            Id = 4,
                            BitTextoActivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BitTextoInactivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BytePosicion = 6,
                            Escala = 1.0,
                            Formato = "0",
                            Nombre = "Estado Inversor",
                            Offset = 0.0,
                            Tag = "EST_INV",
                            TipoVariable = "UINT8",
                            Unidad = "",
                            ValorActual = 1.0,
                            ValorInicial = 0.0
                        },
                        new
                        {
                            Id = 5,
                            BitTextoActivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BitTextoInactivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BytePosicion = 7,
                            Escala = 1.0,
                            Formato = "0",
                            Nombre = "Estado Rectificador",
                            Offset = 0.0,
                            Tag = "EST_RECT",
                            TipoVariable = "UINT8",
                            Unidad = "",
                            ValorActual = 0.0,
                            ValorInicial = 0.0
                        },
                        new
                        {
                            Id = 6,
                            BitTextoActivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BitTextoInactivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BytePosicion = 8,
                            Escala = 1.0,
                            Formato = "0",
                            Nombre = "Alarma Temperatura",
                            Offset = 0.0,
                            Tag = "ALARM_TEMP",
                            TipoVariable = "UINT8",
                            Unidad = "",
                            ValorActual = 1.0,
                            ValorInicial = 0.0
                        },
                        new
                        {
                            Id = 7,
                            BitTextoActivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BitTextoInactivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BytePosicion = 9,
                            Escala = 0.01,
                            Formato = "0.01",
                            Nombre = "Potencia Salida",
                            Offset = 0.0,
                            Tag = "P_SALIDA",
                            TipoVariable = "UINT16",
                            Unidad = "kW",
                            ValorActual = 42.899999999999999,
                            ValorInicial = 0.0
                        },
                        new
                        {
                            Id = 8,
                            BitTextoActivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BitTextoInactivo = "[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]",
                            BytePosicion = 11,
                            Escala = 0.01,
                            Formato = "0.01",
                            Nombre = "Frecuencia Red",
                            Offset = 0.0,
                            Tag = "F_RED",
                            TipoVariable = "UINT16",
                            Unidad = "Hz",
                            ValorActual = 26.809999999999999,
                            ValorInicial = 0.0
                        });
                });

            modelBuilder.Entity("ApsMonitor.Models.Window", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Windows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Control",
                            ContentJson = "[]",
                            Descripcion = "Panel de control principal del sistema APS",
                            IsActive = true,
                            Nombre = "Panel Principal APS",
                            Tipo = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Sinópticos",
                            ContentJson = "[]",
                            Descripcion = "Diagrama eléctrico simplificado del sistema APS",
                            IsActive = true,
                            Nombre = "Sinóptico Eléctrico APS",
                            Tipo = "Sinóptico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
